#!/usr/bin/env bash
# Shared path defaults for EviScreen shell entry points.
#
# Override any value from the environment, or edit this file for a local setup.
# Release code should keep these defaults portable and avoid private host paths.

EVISCREEN_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

EVISCREEN_ENV_ROOT="${EVISCREEN_ENV_ROOT:-}"
if [[ -n "${EVISCREEN_ENV_ROOT}" ]]; then
  EVISCREEN_DEFAULT_BANK_PYTHON_BIN="${EVISCREEN_ENV_ROOT}/env_bank/bin/python"
  EVISCREEN_DEFAULT_REASONING_PYTHON_BIN="${EVISCREEN_ENV_ROOT}/env_reasoning/bin/python"
else
  EVISCREEN_DEFAULT_BANK_PYTHON_BIN="python"
  EVISCREEN_DEFAULT_REASONING_PYTHON_BIN="python"
fi

EVISCREEN_BANK_PYTHON_BIN="${EVISCREEN_BANK_PYTHON_BIN:-${EVISCREEN_PYTHON_BIN:-${EVISCREEN_DEFAULT_BANK_PYTHON_BIN}}}"
EVISCREEN_REASONING_PYTHON_BIN="${EVISCREEN_REASONING_PYTHON_BIN:-${EVISCREEN_DEFAULT_REASONING_PYTHON_BIN}}"
EVISCREEN_PYTHON_BIN="${EVISCREEN_PYTHON_BIN:-${EVISCREEN_BANK_PYTHON_BIN}}"
EVISCREEN_RAW_ROOT="${EVISCREEN_RAW_ROOT:-${EVISCREEN_ROOT}/data/raw_dataset}"
EVISCREEN_STAGE0_OUTPUT_ROOT="${EVISCREEN_STAGE0_OUTPUT_ROOT:-${EVISCREEN_ROOT}/stage_0_data_preparation/fundus_csv}"
EVISCREEN_STAGE1_OUTPUT_DIR="${EVISCREEN_STAGE1_OUTPUT_DIR:-${EVISCREEN_ROOT}/stage_1_dual_knowledge_bank_construction/experiments}"
EVISCREEN_STAGE1_DEBUG_OUTPUT_DIR="${EVISCREEN_STAGE1_DEBUG_OUTPUT_DIR:-${EVISCREEN_STAGE1_OUTPUT_DIR}/debug_50}"
EVISCREEN_CHECKPOINT="${EVISCREEN_CHECKPOINT:-${EVISCREEN_ROOT}/stage_1_dual_knowledge_bank_construction/ckpt/RETFound_dinov2_meh.pth}"
EVISCREEN_STAGE2_OUTPUT_DIR="${EVISCREEN_STAGE2_OUTPUT_DIR:-${EVISCREEN_ROOT}/stage_2_evidential_reasoning/experiments}"
EVISCREEN_STAGE2_RETRIEVED_DATA_DIR="${EVISCREEN_STAGE2_RETRIEVED_DATA_DIR:-${EVISCREEN_STAGE2_OUTPUT_DIR}/retrieved_data}"
EVISCREEN_STAGE2_HEAD_OUTPUT_DIR="${EVISCREEN_STAGE2_HEAD_OUTPUT_DIR:-${EVISCREEN_STAGE2_OUTPUT_DIR}/head_result}"
EVISCREEN_STAGE2_HEAD_CHECKPOINT="${EVISCREEN_STAGE2_HEAD_CHECKPOINT:-${EVISCREEN_STAGE2_HEAD_OUTPUT_DIR}/checkpoint-best_auroc.pth}"
